### ISSUE TITLE
need help to port aggligator to golang

### ISSUE THREAD

**Issue by uoosef** [surban/aggligator#1]
hi,

I am from Iran, and we are suffering from heavy filtering and slow internet speed.

Your awesome project can help us circumvent these restrictions. I'm currently working on a new proxy in Golang, and I want to use your project for "muxing," or multiplexing, my proxy packets between client and server in order to achieve higher speed and a more resilient network connection. Can you help us port your project to Golang?

**Comment by surban** [comment]
Hello,

I greatly appreciate your reaching out and acknowledge the significant effort you're putting into your project. I understand the challenges you're facing and I'm glad that you find my project valuable for your situation.

Regrettably, I don't have the necessary experience with Golang to assist in porting the project directly. However, there are a couple of potential routes you might consider.

One possibility is to build a C API for Aggligator, which can then be interfaced with your Golang project using FFI. This could provide a practical bridge between the two languages, allowing you to leverage Aggligator in your current project. You would still need to write a bit of Rust code, but the effort seems manageable.

Alternatively, you might consider porting your proxy to Rust. Rust, being a more advanced and robust language than Go, could potentially offer you more flexibility and efficiency. Additionally, I'm well-versed in Rust and could provide more effective assistance and advice if you chose this route.

However, the choice ultimately lies with you and depends on your personal preference and proficiency with these languages. Both approaches have their merits.

I wish you all the best with your project, and please don't hesitate to reach out if you have further questions!

**Comment by surban** [comment]
Currently writing detailed design documents is out of question due to time constraints.

However, the main idea is to perform credit-based flow control over each link while dynamically updating the maximum number of outstanding (unacknowledged) bytes for each link. Many approaches are possible here and the best solution depends on the exact characteristics of the network. You can gain some background information by searching for papers and articles on MPTCP window scaling.
