### ISSUE TITLE
Doesn't build on FreeBSD

### ISSUE THREAD

**Issue by cmspam** [surban/aggligator#6]
See here:

https://github.com/ikatson/rqbit/pull/53/files

There's an issue with network-interface that causes it to not build on BSD.
Unfortunately, it works into further issues using the fork they use, because we end up with this:
```

   --> aggligator-util/src/transport/tcp.rs:485:21
    |
485 |                 let Some(addr) = ifn.addr else { continue };
    |                     ^^^^^^^^^^   -------- this expression has type `Vec<Addr>`
    |                     |
    |                     expected `Vec<Addr>`, found `Option<_>`
    |
    = note: expected struct `Vec<Addr>`
                 found enum `Option<_>`



```

**Comment by PaperStrike** [comment]
The build error can be fixed with #3 on Windows, it may also help BSD. Umm, you may meet #4 later on.

**Comment by surban** [comment]
Please try with aggligator-util 0.12.1.

**Comment by cmspam** [comment]
Thank you. I have tried. Initially we get this error (same as before):

```
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/network-interface-1.1.1/src/target/getifaddrs.rs:25:18
   |
25 |         unsafe { libc::freeifaddrs(self.base) }
   |                  ^^^^ use of undeclared crate or module `libc`


```
Of course this is not a problem with aggligator, rather a problem with network-interface (but since aggligator is REALLY useful for any OS that doesn't support MPTCP like FreeBSD, I think it would be really nice to get it working, perhaps without using network-interface if at all possible to ensure the compatibility.)

We then try using the branch of network-interface that compiles on BSD mentioned in my first post

And we get a successful build. But running agg-speed client we get 
`Error: No connection transports.`

And running as server, we get a blank screen with no interfaces shown.

I think that it's just incompatible with FreeBSD and network-interface, honestly.

**Comment by surban** [comment]
Why not contribute FreeBSD support to network-interface? They aim to be cross-platform and are surely open to contributions. 

Since you are familiar it should be pretty straightforward to implement support for it, given that other UNIXes (MacOS, Linux) are already supported.

**Comment by cmspam** [comment]
It's been a while. I just want to give you a HUGE thank you. Aggligator is life-changing for my use case. I've had to depend on mptcp, which means always running linux VMs or linux, always making sure that mptcp is supported, doing various workarounds...

I've just done a bit of testing (albeit linux-based) for all of the workloads that I use MPTCP for, and aggligator actually is on par with or even outperforms the previous mptcp implementations in many cases!

I also want to thank you for your PR to get FreeBSD working with network-interface.

I will continue to experiment with aggligator over the upcoming days, particularly with BSD.

Again, a huge thanks.

**Comment by cmspam** [comment]
And an update, I can confirm that with your patch to network-interface it works on FreeBSD. I was able to build it, and run the features from the utility.

Unfortunately, for whatever reason, the network performance when built on FreeBSD (at least in a virtual machine) is considerably worse than on Linux on the same machine/network. But I haven't yet tested on bare metal, and there could be other variables at play of course.

**Comment by surban** [comment]
Could you check with the `raw-speed` tool for aggligator-util on FreeBSD for comparison?

**Comment by surban** [comment]
> For whatever reason, unfortunately, performance is not good in FreeBSD. Neither natively, nor with the Linux binary compatibility layer. I guess something is just too different architecturally. 600-800mbps with iperf3 but only 50mbps with aggligator speed test, while Linux shows 1200-1500mbps with dual connections to the same server with aggligator speed test.
> 

Are you sure you are using a release build?

I have 300 MB/s upstream and 900 MB/s downstream between Linux and a FreeBSD 14 VM using `agg-speed`.

**Comment by cmspam** [comment]
So, I hadn't tried since your last version release, so I gave it another try in both Linux and FreeBSD VMs running on the same computer with the same specs, speed testing to the same remote server.

The speeds vary a lot with the speed test, but this is more or less the highest speed I see after a few seconds.

Linux: TX 80MB/s RX 160MB/s
FreeBSD: TX 20MB/s RX 80MB/s

I made some configuration changes on the FreeBSD VM in sysctl.conf but I didn't find any difference.

I might note that 80MB/s is basically the max I can get with one of the connections.

VM -> VM on the same machine was slower, due to CPU bottlenecks.

I suspect that this has to do with bugs with FreeBSD and virtio network drivers, however. So I will make some time soon to try on bare metal.

**Comment by surban** [comment]
Strange, my rates are much higher. What VM hypervisor are you using? I use KVM with virt-manager GUI.

**Comment by cmspam** [comment]
> Strange, my rates are much higher. What VM hypervisor are you using? I use KVM with virt-manager GUI.

I am using KVM/qemu also, but managed with incus.
But the hardware is not powerful. It's just celeron N5100. Still, it is enough for a Linux VM to show good performance, and for other software in FreeBSD to show higher network performance with curl/iperf/other network utilities, so it's kind of a mystery to me.

Still, I have seen cases where FreeBSD network performance is horrible, until it is run on bare metal due to issues with hardware offloading on virtio, and I wouldn't rule that out as the cause, so I really need to get around to trying it on other machines and/or bare metal soon to see if there is a big difference.

**Comment by cmspam** [comment]
After some more testing on FreeBSD:

With only one connection to the server, as opposed to two or more, the speed is actually better. I get around 90MBPS on the 1gigabit connection. 30-50 MBPS currently with two 1gbps connections. On linux, these connections combine properly for higher speed. On Mac OS X, I also built and tested. If I turn on Wifi and ethernet (ethernet is the priority connection), the speed is not great. It's similar to max wifi speed. If I disable wifi and use only ethernet, I can get full speed from the two combined 1gbps links. This mac issue may be separate, but while it does split the connections with wifi and ethernet, it does not combine the speed, and just maxes out at the lower of the speeds.

I thought maybe this applied also freebsd so I tried with only one connection, but routed across two 1gbps connections. However, the speed issue is the same. I am still on VMs though. Tomorrow or on the weekend when I have more time, I will try testing more on physical hardware.

**Comment by cmspam** [comment]
I put FreeBSD on a cloud server (aarch64) in order to give some more testing.

Unfortunately, I got a compile error:
```
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/network-interface-1.1.2/src/target/unix/mod.rs:75:31
    |
75  |     let len = unsafe { strlen(data as *const i8) };
    |                        ------ ^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
    |                        |
    |                        arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: function defined here
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/mod.rs:541:12
    |
541 |     pub fn strlen(cs: *const c_char) -> size_t;
    |            ^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `network-interface` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `aggligator-util v0.14.0`, intermediate artifacts can be found at `/tmp/cargo-installCHLPdm`.
```

**Comment by cmspam** [comment]
Using:
network-interface = { git = 'https://github.com/ikatson/network-interface', branch = "compile-on-freebsd" }

I was able to build it on aarch64 FreeBSD, and the speed test results are promising. They seem to be equal to Linux in this case. So I believe it's likely that my issues stemmed from, probably, VM-related issues.

**Comment by cmspam** [comment]
Regarding the speed issues, I can confirm that they are not issues. Using bare metal hardware, speed is as good as linux.

**Comment by cmspam** [comment]
I have been doing more tests on FreeBSD on bare metal.
I have noticed the following problems:

1. IPV6 does not work. Cannot resolve address errors.
2. There are, after all, some severe performance problems.

About the performance problems:
When using an arm64 server with a single fast internet connection and connecting with a linux client, the speeds were as expected, very fast. This is when i made my previous report about no speed problems.
When using dual internet connections on a freebsd client, the speed is roughly 1/3 of what is to be expected, even on bare metal, just as was on virtual machine.

So I think the performance problems are related to the situations where the connections need to be 'aggligated' only, and will only come out under those circumstances.

Testing on linux both server and client, the expected speeds are achieved.
