### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by airfield20** [surban/aggligator#7]
Is there any documentation for how to use the tunneling tool? I'm aware we can just read the code to learn how it parses and figure out what the proper commands are but just a list of a few examples commands would be helpful.

**Comment by surban** [comment]
Do you mean `agg-tunnel`?

**Comment by surban** [comment]
See [`agg-speed`](https://github.com/surban/aggligator/blob/master/docs/agg-speed.md) and [`agg-tunnel`](https://github.com/surban/aggligator/blob/master/docs/agg-tunnel.md) for documentation.

Furthermore all command line tools support the `--help` option.

**Comment by airfield20** [comment]
An example setup showing the tools configured to work with a tcp server or something would be great. I've tried several combinations of commands so far.

Maybe you could answer a few questions for me.

1. Are the agg-tunnel server and agg-tunnel client meant to be connected to each other or used individually?
2. What flag do i use to specify the interfaces I want to aggregate?

I have a tcp server running on a machine A with 2 wifi interfaces (that I want to be aggregated) running on port 9090. It has 2 separate IP addresses. 192.168.1.2 and 192.168.1.3. I have machine B with a single network interface that wants to connect to the server on A:9090. Whats the correct commands to run on each machine to get this running?

**Comment by surban** [comment]
On machine A run:

    agg-tunnel server --port 9090 --tcp 9095

On machine B run:

    agg-tunnel client --port 9090 --tcp 192.168.1.2:9095 --tcp 192.168.1.3:9095

Then connect to port 9090 on machine B.

Of course you can change the tunneling port number `9095` to any other port number you prefer.
